name = "aen"
authors = ["Harold Hastings <hhastings@simons-rock.edu", "Anshul Singhvi <asinghvi17@simons-rock.edu>", "Rifah Tasnim <rtasnim18@simons-rock.edu"]
[deps]
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
